### ISSUE TITLE
Some Hyperlinks in README are not working as expected

### ISSUE THREAD

**Issue by hankunxiao** [UBC-MDS/mushroom_classifier#10]
These 2 hyperlinks are not working as expected in the readme

1. The final report can be found [here](https://github.com/UBC-MDS/mushroom_classifier/blob/main).
2. Codebase: MIT License. See [LICENSE.md](https://github.com/UBC-MDS/mushroom_classifier/blob/main/LICENSE.md).
<img width="746" alt="image" src="https://github.com/user-attachments/assets/739e0765-38cf-402c-8365-d665b53910c1">
<img width="746" alt="image" src="https://github.com/user-attachments/assets/3974b80d-d8c4-4c6d-b837-ae0e5be06b06">

**Comment by MasonZhang-MZ** [comment]
Thanks for catching that, Krabs!

The following 2 hyperlinks in README.md should now work properly.

- The final report can be found [here](https://github.com/UBC-MDS/mushroom_classifier/blob/main/notebooks/Load_Data_and_EDA.ipynb).
- Codebase: MIT License. See [LICENSE.md](https://github.com/UBC-MDS/mushroom_classifier/blob/main/LICENSE).
