### ISSUE TITLE
main branch UPDATE

### ISSUE THREAD

**Issue by y1chi-z** [UBC-MDS/mushroom_classifier#14]
I've accidentally updated the data validation part to the main branch. Please use `git pull` before working or changing anything in the notebook😊 I'll create a new branch for data validation and open a pull request for the code updates.

**Comment by hankunxiao** [comment]
> I've accidentally updated the data validation part to the main branch. Please use `git pull` before working or changing anything in the notebook😊 I'll create a new branch for data validation and open a pull request for the code updates.

Thanks Essie for bring this to our attention. We have been following your recommended practice while working on milestone 2. I am going to close this issue as we are concluding this milestone.
