### ISSUE TITLE
How to run web app in docker container

### ISSUE THREAD

**Issue by bfrizzell01** [UBC-MDS/mushroom_classifier#16]
* In the repo directory run the command `docker compose up`
* Look for the given URL: `http://127.0.0.1:8888/lab?token=...` and copy-paste into your internet browser
Note: I included an image of the terminal output which can be included in the README

**Comment by hankunxiao** [comment]
I have tested it out on my Mac and it worked as expected! thanks for setting up the docker container Ben!
