### ISSUE TITLE
Potential Improvement for `environment.yml` and `Dockerfile`

### ISSUE THREAD

**Issue by MasonZhang-MZ** [UBC-MDS/mushroom_classifier#17]
Thanks for setting up the environment @bfrizzell01. Just spotted 2 small issues:

1. `deepchecks` version confirmation in `environment.yml`
2. Automate the installation for `deepchecks` in `Dockerfile`

Please see comments on `environment.yml` and `Dockerfile` for detail.

**Comment by bfrizzell01** [comment]
Thanks @MasonZhang-MZ, I've addressed your comments: https://github.com/UBC-MDS/mushroom_classifier/pull/12
