### ISSUE TITLE
preprocess_script update

### ISSUE THREAD

**Issue by MasonZhang-MZ** [UBC-MDS/mushroom_classifier#23]
### README.md updates for @bfrizzell01
To run the analysis, open a terminal and run the following commands:

`download_data.py`
```
python scripts/download_data.py \
    --dataset_id 848 \
    --raw_path data/raw/raw_mushroom.csv
```
`data_cleaning.py`
```
python scripts/data_cleaning.py \
    --input_path data/raw/raw_mushroom.csv \
    --output_path data/processed/cleaned_mushroom.csv \
    --columns_to_drop_path data/processed/columns_to_drop.csv \
    --missing_values_path results/tables/missing_values_by_column.csv
```
`split_n_preprocess.py`
```
python scripts/split_n_preprocess.py \
    --input_path data/processed/cleaned_mushroom.csv \
    --output_dir data/processed \
    --results_dir results \
    --seed 123
```

### Here are the inputs and outputs for the first 3 scripts: @y1chi-z @hankunxiao 

1. `download_data.py`
- INPUT: 
    - `dataset_id`
- OUTPUT: 
    - `data/raw/raw_mushroom.csv`

2. `data_cleaning.py`
- INPUT: 
    - `data/raw/raw_mushroom.csv`
- OUTPUT: 
    - `data/processed/cleaned_mushroom.csv`
    - `data/processed/columns_to_drop.csv`
    - `results/tables/missing_values_by_column.csv`

3. `split_n_preprocess.py`
- INPUT: 
    - `data/processed/cleaned_mushroom.csv`
- OUTPUT: 
    - `data/processed/mushroom_test.csv`
    - `data/processed/mushroom_train.csv`
    - `data/processed/scaled_mushroom_test.csv`
    - `data/processed/scaled_mushroom_train.csv`
    - `results/figures/target_variable_distribution.png`
    - `results/models/mushroom_preprocessor.pickle`
    - `results/tables/schema_validate.csv`
    - `results/tables/numeric_correlation_matrix.csv`

**Comment by hankunxiao** [comment]
thanks @MasonZhang-MZ 
I just tested it out on my computer. All Good!!
I think it will be very helpful for our readers to replicate the process if we could add this part to the readme file.

**Comment by hankunxiao** [comment]
> thanks @MasonZhang-MZ I just tested it out on my computer. All Good!! I think it will be very helpful for our readers to replicate the process if we could add this part to the readme file.

never mind. I just found them in readme. thanks Mason!
