### ISSUE TITLE
Code Review Suggestions

### ISSUE THREAD

**Issue by bfrizzell01** [UBC-MDS/mushroom_classifier#25]
Hello everyone, here are some potential issues I've found so far:

- [x] Some of scripts, `eda.py`, `evaluate_mushroom_predictor.py`, and `fit_mushroom_classifier.py` are currently in the root directory. We should move them to the `scripts` directory for organization.
- [x] In line 99 of `fit_mushroom_classifier.py`, it looks like the `numeric_correlation_matrix.csv` file from `split_n_preprocess.py` is being overwritten by the cross validation table. We should fix this by changing the name of the saved CSV file to something like `cv_results.csv`
- [x] Both `evaluate_mushroom_classifier.py` and `fit_mushroom_classifier.py` create `confusion_matrix.png` files. We should make sure they don't overwrite eachother by changing the one produced by `fit_mushroom_classifier.py` to `train_confusion_matrix.png` and the one produced by `evaluate_mushroom_classifier.py` to `test_confusion_matrix.png`
- [x] In line 65 of `eda.py`, I would recommend we save the frequency tables to the `tables` directory, rather than the `figures` directory for consistency. 
- [x] In line 35 of `fit_mushroom_classifier.py`, the `--plot-to` argument seems to be unused in place of `--results-to`. We should remove this to avoid confusion.
- [x] `evaluate_mushroom_classifier.py` should take in the cleaned test data, not the scaled test data. This is because the fitted model includes a preprocessor in the pipeline already.

**Comment by y1chi-z** [comment]
Just one question for the frequency tables: if we save them as tables, there's not gonna be color gradients in the tables, would that be ok for our final report?
