### ISSUE TITLE
Confusion Matrix data discrepancy 

### ISSUE THREAD

**Issue by hankunxiao** [UBC-MDS/mushroom_classifier#27]
Hi Team,
I notice that there is a discrepancy in our confusion matrix for the test data: # False Positive and # False Negative. Shall we update it?
![test_confusion_matrix](https://github.com/user-attachments/assets/8cad09c3-4a87-45a9-89e9-120449b7ba3c)
![image](https://github.com/user-attachments/assets/96e48e01-5b8b-457d-b2e7-db08360c0d84)

**Comment by y1chi-z** [comment]
Yes for sure. I guess this is why we need to download and save the data for reproducibility😂

**Comment by hankunxiao** [comment]
I am using the inline code to improve the consistency: I read the output score csv file and the refer to it as `{python} FN`. I think we just need to update some markdown in the jupyter notebook
